---
- hosts: all
  become: yes
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  tasks:
    - name: "apt-get update"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    - name: "apt-get-upgrade"
      apt:
        upgrade: yes
        cache_valid_time: 3600
    - name: "intall software-properties-common"
      become: yes
      apt:
        name: software-properties-common
        state: present
    - name: "add nodejs apt key"
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    - name: "download node"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x bionic main
        update_cache: yes
    - name: "install node.js"
      apt:
        update_cache: yes
        name: nodejs
        state: present
