---
- name: Install MongoDB and dependencies
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: 'apt get update'
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    - name: 'Software Properties Common'
      become: true
      apt:
        name: software-properties-common
        state: present
    - name: Add Mongo Key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        state: present
    - name: Add Mongo Repository
      apt_repository:
        repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse'
        update_cache: true
    - name: Add NodeJS V16 Repository
      shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      become: true
    - name: Install NodeJS
      apt:
        name: nodejs
        update_cache: true
        state: present
    - name: Install MongoDB
      apt:
        name: mongodb-org
        update_cache: true
        state: present
    - name: Start Mongo Service
      service:
        name: mongod
        state: started
    - name: Enable Mongo Service on Boot
      service:
        name: mongod
        enabled: yes
    - name: Copy Mongo Config
      copy:
        src: ./env/mongodb/mongod.conf
        dest: /etc/mongod.conf
    - name: Restart Mongo Service
      service:
        name: mongod
        state: restarted
    - name: Copy IP
      shell: hostname -I > /home/vagrant/global/hostname.txt
      become: true
    - name: Install Dependencies and Start DB
      shell: |
        npm install -g npm
        npm install -g forever
        cd scoreApi
        npm install
        forever start server.js
